### ISSUE TITLE
App Issue when selecting Template

### ISSUE THREAD

**Issue by jeff20009** [Jeffchiucp/MemeApp#1]
There's some App Issue when selecting Template. Such as first picture of tank

**Comment by jeff20009** [comment]
See the Meme Template American Shernman Tank

**Comment by Jeffchiucp** [comment]
updated the template Table View

**Comment by Jeffchiucp** [comment]
added Frabrics and tested the Crashlytics

**Comment by Jeffchiucp** [comment]
resolved the issue
