### ISSUE TITLE
Bug. App crashes when selects Meme Template picture

### ISSUE THREAD

**Issue by jeff20009** [Jeffchiucp/MemeApp#2]
There's Bug. App crashes when selects Meme Template picture
2016-10-05 19:35:57.005 MemeMe[1084:17409] [Crashlytics] Version 3.7.3 (114)
fatal error: unexpectedly found nil while unwrapping an Optional value

**Comment by Jeffchiucp** [comment]
updated and added quick-fix. It seems to be for-loop issue that is fixed by testing the for-loop.

**Comment by Jeffchiucp** [comment]
https://www.dropbox.com/s/q8myzlbvt3pi2ts/Screenshot%202016-10-05%2020.22.49.png?dl=0

**Comment by Jeffchiucp** [comment]
<img width="1277" alt="screenshot 2016-10-05 20 22 49" src="https://cloud.githubusercontent.com/assets/10523517/19139779/4eb6894e-8b3c-11e6-906d-6ccff390a0bd.png">
Update my template meme TableView
