### ISSUE TITLE
Issue with Swift 3.0

### ISSUE THREAD

**Issue by jeff20009** [Jeffchiucp/MemeApp#3]
I have some bug with Issue with Swift 3.0.
App is not running after Swift 3.0 update

**Comment by jeff20009** [comment]
The target “Meme App” contains source code developed with an earlier version of Swift.

Choose “Convert” to update the source code in this target to the latest SDKs. You will be given the choice to use Swift 2.3 syntax or update to Swift 3.

This action can be performed later using “Conversion"

**Comment by jeff20009** [comment]
“Use Legacy Swift Language Version” (SWIFT_VERSION) is required to be configured correctly for targets which use Swift. Use the [Edit > Convert > To Current Swift Syntax…] menu to choose a Swift version or use the Build Settings editor to configure the build setting directly.

@Jeffchiucp

**Comment by Jeffchiucp** [comment]
fixed the bug and syntax for Swift 3.0

**Comment by jeff20009** [comment]
Thank you. @Jeffchiucp
